# Generated by Django 4.2.7 on 2024-03-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachingapp', '0003_customer_bday_alter_customer_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bday',
            field=models.DateField(),
        ),
    ]
