# Generated by Django 4.2.7 on 2024-03-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachingapp', '0004_alter_customer_bday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
